# Enables the plugin
torchlight-enabled: true

# Time in seconds that the torchlight will last between movements. Default: 10
light-timer-seconds: 10

# Light level (1-15). Default: 15
light-level: 15
