name: Build and Attach to Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Extract version from release
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Build with Maven
        env:
          VERSION: ${{ env.VERSION }}
        run: mvn clean package -Drevision=$VERSION

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: target/offhand-torch-light-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
